In [1]:
#

import pandas as pd
import numpy as np
volunteer = pd.read_csv('/content/heart failur classification dataset.csv')
volunteer.head(10)

   Unnamed: 0   age  anaemia  ...  smoking  time  DEATH_EVENT
0           0  75.0        0  ...       No   4.0            1
1           1  55.0        0  ...       No   6.0            1
2           2  65.0        0  ...      Yes   7.0            1
3           3  50.0        1  ...       No   7.0            1
4           4  65.0        1  ...       No   8.0            1
5           5  90.0        1  ...      Yes   8.0            1
6           6  75.0        1  ...       No  10.0            1
7           7  60.0        1  ...      Yes  10.0            1
8           8  65.0        0  ...       No  10.0            1
9           9  80.0        1  ...      Yes  10.0            1

[10 rows x 14 columns]

In [ ]:
volunteer.shape

(299, 14)

In [ ]:
volunteer.isnull().sum()

Unnamed: 0                  0
age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                6
sex                         0
smoking                     0
time                        7
DEATH_EVENT                 0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer

impute = SimpleImputer(missing_values=np.nan, strategy='mean')

impute.fit(volunteer[['time']])

volunteer['time'] = impute.transform(volunteer[['time']])

In [ ]:
from sklearn.impute import SimpleImputer

impute = SimpleImputer(missing_values=np.nan, strategy='mean')

impute.fit(volunteer[['serum_sodium']])

volunteer['serum_sodium'] = impute.transform(volunteer[['serum_sodium']])

In [ ]:
volunteer.isnull().sum()

Unnamed: 0                  0
age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [ ]:
volunteer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                299 non-null    int64
 1   age                       299 non-null    float64
 2   anaemia                   299 non-null    int64
 3   creatinine_phosphokinase  299 non-null    int64
 4   diabetes                  299 non-null    int64
 5   ejection_fraction         299 non-null    int64
 6   high_blood_pressure       299 non-null    int64
 7   platelets                 299 non-null    float64
 8   serum_creatinine          299 non-null    float64
 9   serum_sodium              299 non-null    float64
 10  sex                       299 non-null    object
 11  smoking                   299 non-null    object
 12  time                      299 non-null    float64
 13  DEATH_EVENT               299 non-null    int64
dtypes: float64(5), int64(7), object(2)
memory usage: 32.8+ KB

In [ ]:
volunteer.head()

   Unnamed: 0   age  anaemia  ...  smoking  time  DEATH_EVENT
0           0  75.0        0  ...       No   4.0            1
1           1  55.0        0  ...       No   6.0            1
2           2  65.0        0  ...      Yes   7.0            1
3           3  50.0        1  ...       No   7.0            1
4           4  65.0        1  ...       No   8.0            1

[5 rows x 14 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder


enc = LabelEncoder()


volunteer['sex_enc'] = enc.fit_transform(volunteer['sex'])
volunteer['smoking_enc']=enc.fit_transform(volunteer['smoking'])


# Compare the two columns
print(volunteer[['sex', 'sex_enc']].head())

      sex  sex_enc
0    Male        1
1    Male        1
2    Male        1
3    Male        1
4  Female        0

In [ ]:
print(volunteer[['smoking','smoking_enc']].head())

  smoking  smoking_enc
0      No            0
1      No            0
2     Yes            1
3      No            0
4      No            0

In [ ]:
volunteer.head()

   Unnamed: 0   age  anaemia  ...  DEATH_EVENT  sex_enc  smoking_enc
0           0  75.0        0  ...            1        1            0
1           1  55.0        0  ...            1        1            0
2           2  65.0        0  ...            1        1            1
3           3  50.0        1  ...            1        1            0
4           4  65.0        1  ...            1        0            0

[5 rows x 16 columns]

In [ ]:
volunteer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                299 non-null    int64
 1   age                       299 non-null    float64
 2   anaemia                   299 non-null    int64
 3   creatinine_phosphokinase  299 non-null    int64
 4   diabetes                  299 non-null    int64
 5   ejection_fraction         299 non-null    int64
 6   high_blood_pressure       299 non-null    int64
 7   platelets                 299 non-null    float64
 8   serum_creatinine          299 non-null    float64
 9   serum_sodium              299 non-null    float64
 10  sex                       299 non-null    object
 11  smoking                   299 non-null    object
 12  time                      299 non-null    float64
 13  DEATH_EVENT               299 non-null    int64
 14  sex_enc                   299 non-null    int64
 15  smoking_enc               299 non-null    int64
dtypes: float64(5), int64(9), object(2)
memory usage: 37.5+ KB

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
X_train, X_test, y_train, y_test = train_test_split(volunteer, volunteer, random_state=1)
print(X_train.shape)
print(X_test.shape)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)

print("per-feature minimum after scaling:\n {}".format(X_train_scaled.min(axis=0)))

print("per-feature maximum after scaling:\n {}".format(X_train_scaled.max(axis=0)))

(224, 14)
(75, 14)

ValueError: ignored

# New section